# Generated by Django 3.0.3 on 2020-02-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='bezeichnung',
            new_name='name',
        ),
    ]
