# Generated by Django 3.0.3 on 2020-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20200223_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='min',
        ),
        migrations.AddField(
            model_name='alarm',
            name='time',
            field=models.CharField(default='11:00', max_length=25),
            preserve_default=False,
        ),
    ]
