# Generated by Django 3.0.3 on 2020-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20200223_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='weekdays',
            field=models.CharField(max_length=28),
        ),
    ]
